### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [maxrimue/combijson#26]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@waelahmed-dev) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by maxrimue** [comment]
Hello @JamieSlome,

thanks for your message. As this repository has been missing maintenance in general and is no longer of much use (its main feature, prioritzed object merging, can be done via builtin language features nowadays easily), I would instead opt for archiving and deprecating the package, so I do not plan to put any further work into the issue.

I think the deprecation causes a warning for anyone using the package. I'm still interested to know what the underlying issue is, and, if it is severe, I guess it can also be reported to npm to further discourage use of the package? But yes, feel free to shoot me an email via max.rittmueller@gmail.com if you want to share any details. Good pointer to the documentation, will keep that in mind.

Thanks!
